### PR TITLE
Autocomplete enhancements

### PR DESCRIPTION
**Pull request by stardust66**
- Complete attribute names that have spaces in them with backticks.
- When completing function names, move cursor between the parentheses after completion, just like the CODAP editor does.

### CODE REVIEW

**Comment by thomascastleman** [comment]
For some reason I'm getting this error:

Screenshot from 2021-08-02 14-05-36

I made a multi word attribute and then tried to use it in the transform formula. It seems to think something is a function?

**Comment by stardust66** [comment]
That's a CODAP side issue and it has been fixed. The error should go away if you update your local codap.

**Comment by stardust66** [comment]
FYI, it's because it's compiling it to `multiplyFunction(c.vars.Multi Word Attribute, 10)` and not using square brackets.

**Review by thomascastleman — APPROVED** [review]
Awesome, it works now. These both really augment the usability of the expression editor. 👍🏻

**Review by P-bibs — APPROVED** [review]
:+1: Agree with Thomas, this makes the expression editor way better since no one's going to know they have to use backticks

**Pull request merged**
