### PR TITLE
Extract error message strings

### PR DESCRIPTION
**Pull request by stardust66**
- Use `i18next`, an internationalization library.
- Extract all error messages from components into a single file.

This will also make translation in the future easier. In the short term it helps with keeping track of all our error messages.

### CODE REVIEW

**Review by thomascastleman — APPROVED** [review]
Nice, I like how this removes a lot of redundancy among the transformers with similar UI checks. 

Have the changes from the Google doc already been applied or are we waiting on more feedback there?

**Review by P-bibs — APPROVED** [review]
Looks good to me! (or should I say sieht gut für mich aus?)

**Comment by P-bibs** [comment]
Let me know if any of the merge conflicts take too long and you need a second hand

**Comment by stardust66** [comment]
> Have the changes from the Google doc already been applied or are we waiting on more feedback there?

I only applied one change. I'm not sure if Emmanuel's done with reviewing yet.

**Pull request merged**
