### PR TITLE
Support two kinds of sort

### LINKED ISSUE #224: Sort Transformer - description/UI
- [ ] What’s the difference between a “key expression” and a “formula expression”? If there is one, can it be explained here?
- [ ] What’s needed is not really an expression at all - it’s an attribute. 
- [ ] Also, the Domain of Sort ought to be “Table" -- but "row" is provided.

### PR DESCRIPTION
**Pull request by stardust66**
Resolves #224.

Changes:
- Add toggle component which is a dropdown where each option hides certain other components.
- Add sorting by attribute.

TODO:
- [x] Initialization issue: toggle value (by attribute or by expression) is initialized to null, even though it looks like it is set to "byAttribute" by default. If the user does not touch the toggle, sort will fail because toggle is null.
- [x] Comparison function issue: we need to be looser with types in our comparison function. Currently we do not detect numeric strings and sort them as strings instead.

### CODE REVIEW

**Comment by stardust66** [comment]
Available for testing here: https://codap.concord.org/app/static/dg/en/cert/index.html?di=https://idyllic-cat-9dfb8b.netlify.app/

**Review by thomascastleman — APPROVED** [review]
Looks great!

**Comment by retabak** [comment]
Just seeing this! Yay! Two types of Sort!
My one issue that when you click on "Sort method," whichever method is selected appears twice. 

Screenshot (1)

**Comment by stardust66** [comment]
> My one issue that when you click on "Sort method," whichever method is selected appears twice.
Just fixed this! The preview should be updated as well.

**Comment by retabak** [comment]
yay! Looks good to me.

**Review by P-bibs — APPROVED** [review]

**Pull request merged**
