### PR TITLE
Redo transformer categories

### PR DESCRIPTION
**Pull request by P-bibs**
Waiting to finalize until we get feedback on google doc

### CODE REVIEW

**Comment by thomascastleman** [comment]
To do:
- [x] Individual transformers renames (mean, transform col, etc)
- [ ] Reorder transformers + update categories
- [ ] Update standalone documentation to be consistent

**Comment by thomascastleman** [comment]
Should be good to go, barring the controversial "Building" category, which should be easy to change later if need be.

**Comment by thomascastleman** [comment]
Okay, this seems ready now that that's settled. @stardust66 @P-bibs

**Review by stardust66 — APPROVED** [review]
Looks good.

**Pull request merged**
